### ISSUE TITLE
no attribute 'TableWidget' in module 'gui'

### ISSUE THREAD

**Issue by ShawnXuan** [biolab/orange3-datafusion#16]
Hi,

When I use the data fusion widget, it raises error below, please help to solve, thanks!

Could not create 'Fusion Graph'

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\Orange\canvas\scheme\widgetsscheme.py", line 341, in create_widget_instance
    widget.**init**()
  File "C:\Python34\lib\site-packages\orangecontrib\datafusion\widgets\owfusiongraph.py", line 92, in **init**
    self._create_layout()
  File "C:\Python34\lib\site-packages\orangecontrib\datafusion\widgets\owfusiongraph.py", line 128, in _create_layout
    self.table = gui.TableWidget(info, select_rows=True)
AttributeError: 'module' object has no attribute 'TableWidget'

BR
Shawn

**Comment by ajdapretnar** [comment]
@ShawnXuan Hi Shaun, yes, we've been doing some code refactoring and haven't managed to fix all add-ons just yet. We're certainly working on it, sorry for the inconvenience!

**Comment by ShawnXuan** [comment]
Thanks! Understand!
It's a very powerful and beautiful software.
2016年5月5日 上午2:25，"Ajda" notifications@github.com写道：

**Comment by kernc** [comment]
If you need it urgently, [version 3.3.1](http://orange.biolab.si/download/files/) should work.

**Comment by ShawnXuan** [comment]
yes, 3.3.1 works!

Thanks!
2016年5月5日 上午8:56，"kernc" notifications@github.com写道：

**Comment by astaric** [comment]
Orange 3.3.4 and Orange3-DataFusion 0.1.10 have been released and published on PyPi. If you update both, you should be able to use the widgets.
