### ISSUE TITLE
Please define the license

### ISSUE THREAD

**Issue by yurivict** [biolab/orange3-datafusion#28]

**Comment by toddrme2178** [comment]
I would like to package this for openSUSE, but I cannot do so unless there is a license.

**Comment by PrimozGodec** [comment]
@kernc @ajdapretnar what license should we add here?

**Comment by kernc** [comment]
I guess the license of the rest of the suite?

**Comment by ajdapretnar** [comment]
I agree. https://github.com/biolab/orange3/blob/master/LICENSE
