### ISSUE TITLE
Installation process for Data Fusion widget in Orange3 

### ISSUE THREAD

**Issue by ghost** [biolab/orange3-datafusion#30]
I am trying to install the data fusion add on in Orange but I am unable to do so. I have tried using this link to download on windows 10 (https://biolab.github.io/datafusion-installation-guide/#testing) and also using the read me file in the data fusion repository. But none of them works. I have rebooted the PC to complete the installation but it still doesn't work. So my question is, is Data Fusion stable version released and also where can I find the documentation for it? And can anyone point me to the right steps for installing the add on.

Thank you

**Comment by BlazZupan** [comment]
yogesh, sorry, this add-on to Orange is provided as is and we no longer actively maintain it.
